### PR TITLE
xtd/network/server/tools.py:

### PR DESCRIPTION
**Pull request by Anvil**
log_request_response: minor formatting changes, removed some branches, pseudo-dead code

### CODE REVIEW

**Comment by Anvil** [comment]
There was a pylint warning about "too many branches" in that function. Thought you'd like to clean that.

Also, note that there's a slight penalty in execution time with "private functions". See, there are not functions but "closures" (a.k.a functions defined in a given environment). "Private functions" get defined _every time_ the function containing them is called.

**Comment by psycofdj** [comment]
Automatic build report for commit d20218e2e812b237ef2eea2fe660e2d0095cd820:

[Unit Tests](#)
[PyLint](#)
[Documentation](#)

**Comment by psycofdj** [comment]
Automatic build report for commit d20218e2e812b237ef2eea2fe660e2d0095cd820:

[Unit Tests](#)
[PyLint](#)
[Documentation](#)

**Comment by psycofdj** [comment]
Automatic build report for commit d20218e2e812b237ef2eea2fe660e2d0095cd820:

[Unit Tests](#)
[PyLint](#)
[Documentation](#)

**Comment by psycofdj** [comment]
Automatic build report for commit 599151c04e46ea1171f073ca47f4ed1752e4c9f4:

[Unit Tests](#)
[PyLint](#)
[Documentation](#)

**Comment by psycofdj** [comment]
Automatic build report for commit 599151c04e46ea1171f073ca47f4ed1752e4c9f4:

[Unit Tests](#)
[PyLint](#)
[Documentation](#)

**Pull request merged**
